version: '3.8'

services:

  discovery-server:
    build: ./Discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: always

  gateway-server:
    build: ./GateWay-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    restart: always

  product-db:
    image: postgres:16
    container_name: product-db
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - product-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  product-server:
    build: ./Product-server
    container_name: product-server
    environment:
      - DB_URL=jdbc:postgresql://product-db:5432/products
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      product-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    restart: always

  order-db:
    image: postgres:16
    container_name: order-db
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - order-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-server:
    build: ./Order-server
    container_name: order-server
    environment:
      - DB_URL=jdbc:postgresql://order-db:5432/orders
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      order-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    restart: always

  cart-db:
    image: postgres:16
    container_name: cart-db
    restart: always
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cart-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cart-server:
    build: ./Cart-server
    container_name: cart-server
    environment:
      - DB_URL=jdbc:postgresql://cart-db:5432/cart
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      cart-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    restart: always

  user-db:
    image: postgres:16
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-server:
    build: ./AuthForge
    container_name: auth-server
    environment:
      - DB_URL=jdbc:postgresql://user-db:5432/user
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      user-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - product-db
      - order-db
      - cart-db
      - user-db

# تعريف المجلدات الدائمة للحفاظ على البيانات
volumes:
  product-data:
  order-data:
  cart-data:
  user-data: