spring:
  application:
    name: product-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB       # أقصى حجم مسموح للصورة الواحدة (20 ميجا)
      max-request-size: 100MB   # أقصى حجم مسموح للطلب بالكامل (مثلاً لو رفعت 5 صور معاً)

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}