spring.application.name=cart-server
spring.datasource.url=jdbc:postgresql://localhost:5432/cart?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
