spring:
  application:
    name: order-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.hostinger.com
    port: 465
    username: info@alkabhawy-gallery.com
    password: M7md@315050344

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true

server:
  port: 9091