spring:
  application:
    name: order-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.hostinger.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          # 👈 التعديل الثاني: إضافة إعدادات مصنع الاتصال الآمن بصيغة YAML
          socketFactory:
            port: ${MAIL_PORT:465}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true

server:
  port: 9091